"""
HTML Renderer for Admission Guides.

Renders a guide as a completely self-contained HTML page with inline CSS
and JS. Uses a professional, clean design with dark navy headers, white
content areas, and accent colors.
"""

import html
import re
from datetime import datetime
from typing import Any


def render_guide_html(guide: dict[str, Any]) -> str:
    """Render a full admission guide as a self-contained HTML page."""
    university_name = guide.get("university_name", "University")
    generated_at = guide.get("generated_at", "")
    if isinstance(generated_at, datetime):
        generated_at = generated_at.strftime("%B %d, %Y")
    elif isinstance(generated_at, str) and generated_at:
        try:
            generated_at = datetime.fromisoformat(
                generated_at.replace("Z", "+00:00")
            ).strftime("%B %d, %Y")
        except Exception:
            pass

    sections = guide.get("sections", [])
    customization = guide.get("customization", {})
    primary_color = customization.get("primary_color", "#1e3a5f")
    accent_color = customization.get("accent_color", "#3b82f6")
    show_sources = customization.get("show_sources", True)
    show_confidence = customization.get("show_confidence", False)
    show_missing = customization.get("show_missing_sections", True)
    logo_url = customization.get("logo_url")
    custom_header = customization.get("custom_header")
    completeness = guide.get("completeness_score", 0)

    toc_html = _build_toc(sections, show_missing)
    sections_html = "\n".join(
        _render_section(s, show_sources, show_confidence, show_missing, accent_color)
        for s in sections
    )

    logo_tag = ""
    if logo_url:
        logo_tag = f'<img src="{html.escape(logo_url)}" alt="{html.escape(university_name)} logo" class="header-logo" />'

    header_subtitle = html.escape(custom_header) if custom_header else "Admission Guide"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>{html.escape(university_name)} - Admission Guide</title>
<style>
{_get_css(primary_color, accent_color)}
</style>
</head>
<body>

<!-- Header -->
<header class="guide-header">
  <div class="header-inner">
    <div class="header-brand">
      {logo_tag}
      <div>
        <h1 class="header-title">{html.escape(university_name)}</h1>
        <p class="header-subtitle">{header_subtitle}</p>
      </div>
    </div>
    <div class="header-meta">
      <span class="completeness-badge">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>
        Generated {html.escape(str(generated_at))}
      </span>
      <span class="completeness-badge completeness-score">
        {completeness:.0f}% Complete
      </span>
    </div>
  </div>
</header>

<div class="guide-layout">
  <!-- Sidebar TOC -->
  <nav class="guide-sidebar" id="guideSidebar">
    <div class="sidebar-inner">
      <div class="toc-header">Table of Contents</div>
      <div class="completeness-bar-wrap">
        <div class="completeness-bar" style="width: {completeness}%"></div>
      </div>
      <ul class="toc-list" id="tocList">
        {toc_html}
      </ul>
    </div>
  </nav>

  <!-- Main Content -->
  <main class="guide-content" id="guideContent">
    {sections_html}

    <div class="watermark">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
      Generated by <strong>UniAudit</strong> &middot; Automated Admission Guide
    </div>
  </main>
</div>

<!-- Mobile TOC Toggle -->
<button class="mobile-toc-toggle" id="mobileTocToggle" aria-label="Toggle table of contents">
  <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
</button>

<script>
{_get_js()}
</script>
</body>
</html>"""


def _build_toc(sections: list[dict], show_missing: bool) -> str:
    items = []
    for s in sections:
        sid = s["id"]
        title = html.escape(s["title"])
        status = s.get("status", "found")
        if status == "missing" and not show_missing:
            continue
        status_class = f"toc-status-{status}"
        icon = _status_icon(status)
        items.append(
            f'<li class="toc-item {status_class}">'
            f'<a href="#{sid}" class="toc-link" data-section="{sid}">'
            f'{icon}<span>{title}</span></a></li>'
        )
    return "\n".join(items)


def _status_icon(status: str) -> str:
    if status == "found":
        return '<span class="toc-icon toc-icon-found"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 6L9 17l-5-5"/></svg></span>'
    if status == "partial":
        return '<span class="toc-icon toc-icon-partial"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg></span>'
    return '<span class="toc-icon toc-icon-missing"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg></span>'


def _render_section(
    section: dict,
    show_sources: bool,
    show_confidence: bool,
    show_missing: bool,
    accent_color: str,
) -> str:
    sid = section["id"]
    title = html.escape(section["title"])
    content = section.get("content", "")
    status = section.get("status", "found")
    source_urls = section.get("source_urls", [])
    confidence = section.get("confidence", 0)
    last_verified = section.get("last_verified")

    if status == "missing" and not show_missing:
        return ""

    status_badge = ""
    section_class = "section"
    if status == "missing":
        section_class += " section-missing"
        status_badge = (
            '<span class="status-badge status-missing">'
            '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
            '<path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/>'
            '<line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>'
            '</svg> Missing from website</span>'
        )
    elif status == "partial":
        section_class += " section-partial"
        status_badge = (
            '<span class="status-badge status-partial">'
            '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
            '<circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/>'
            '<line x1="12" y1="16" x2="12.01" y2="16"/>'
            '</svg> Partial information</span>'
        )

    content_html = _markdown_to_html(content) if content else (
        '<p class="empty-msg">No information was found on the university website for this section.</p>'
    )

    sources_html = ""
    if show_sources and source_urls:
        chips = "".join(
            f'<a href="{html.escape(u)}" target="_blank" rel="noopener" class="source-chip">'
            f'<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">'
            f'<path d="M18 13v6a2 2 0 01-2 2H5a2 2 0 01-2-2V8a2 2 0 012-2h6"/>'
            f'<polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>'
            f'{html.escape(_url_label(u))}</a>'
            for u in source_urls[:5]
        )
        sources_html = f'<div class="source-links"><span class="source-label">Sources:</span>{chips}</div>'

    confidence_html = ""
    if show_confidence:
        pct = int(confidence * 100)
        confidence_html = (
            f'<div class="confidence-bar-wrap">'
            f'<span class="confidence-label">Confidence: {pct}%</span>'
            f'<div class="confidence-track"><div class="confidence-fill" style="width:{pct}%"></div></div>'
            f'</div>'
        )

    verified_html = ""
    if last_verified:
        try:
            vd = datetime.fromisoformat(last_verified.replace("Z", "+00:00"))
            verified_html = f'<span class="verified-date">Last verified: {vd.strftime("%b %d, %Y")}</span>'
        except Exception:
            pass

    return f"""
    <section class="{section_class}" id="{sid}">
      <div class="section-header">
        <h2 class="section-title">{title}</h2>
        <div class="section-badges">{status_badge}{verified_html}</div>
      </div>
      <div class="section-body">{content_html}</div>
      {sources_html}
      {confidence_html}
    </section>"""


def _url_label(url: str) -> str:
    """Extract a short label from a URL."""
    url = url.rstrip("/")
    parts = url.split("/")
    if len(parts) > 3:
        return "/".join(parts[-2:])[:40]
    return url.split("//")[-1][:40]


def _markdown_to_html(text: str) -> str:
    """Simple markdown to HTML conversion for guide content."""
    if not text:
        return ""

    lines = text.split("\n")
    html_lines = []
    in_list = False
    in_table = False
    table_rows: list[str] = []

    for line in lines:
        stripped = line.strip()

        # Table row
        if stripped.startswith("|") and stripped.endswith("|"):
            if not in_table:
                in_table = True
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                table_rows = []
            # Skip separator rows
            if re.match(r"^\|[\s\-:|]+\|$", stripped):
                continue
            cells = [c.strip() for c in stripped.strip("|").split("|")]
            table_rows.append(cells)
            continue
        elif in_table:
            # End table
            html_lines.append(_build_table(table_rows))
            in_table = False
            table_rows = []

        # Headings
        if stripped.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h4>{_inline_md(stripped[4:])}</h4>")
            continue
        if stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3>{_inline_md(stripped[3:])}</h3>")
            continue

        # Bullet list
        if re.match(r"^[-*]\s", stripped):
            if not in_list:
                in_list = True
                html_lines.append("<ul>")
            html_lines.append(f"<li>{_inline_md(stripped[2:])}</li>")
            continue

        # Numbered list
        if re.match(r"^\d+\.\s", stripped):
            content = re.sub(r"^\d+\.\s*", "", stripped)
            if not in_list:
                in_list = True
                html_lines.append("<ul class='numbered'>")
            html_lines.append(f"<li>{_inline_md(content)}</li>")
            continue

        # Close list if not a list item
        if in_list:
            html_lines.append("</ul>")
            in_list = False

        # Empty line -> paragraph break
        if not stripped:
            html_lines.append("")
            continue

        # Regular paragraph
        html_lines.append(f"<p>{_inline_md(stripped)}</p>")

    if in_list:
        html_lines.append("</ul>")
    if in_table and table_rows:
        html_lines.append(_build_table(table_rows))

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline markdown (bold, italic, links, code)."""
    text = html.escape(text)
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    # Code
    text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
    # Links - already escaped, so unescape the URL part
    text = re.sub(
        r"\[(.+?)\]\((.+?)\)",
        lambda m: f'<a href="{html.unescape(m.group(2))}" target="_blank" rel="noopener">{m.group(1)}</a>',
        text,
    )
    return text


def _build_table(rows: list[list[str]]) -> str:
    """Build an HTML table from parsed rows."""
    if not rows:
        return ""
    header = rows[0]
    body = rows[1:] if len(rows) > 1 else []
    thead = "<tr>" + "".join(f"<th>{_inline_md(c)}</th>" for c in header) + "</tr>"
    tbody_rows = []
    for row in body:
        cells = "".join(f"<td>{_inline_md(c)}</td>" for c in row)
        tbody_rows.append(f"<tr>{cells}</tr>")
    tbody = "\n".join(tbody_rows)
    return f'<div class="table-wrap"><table><thead>{thead}</thead><tbody>{tbody}</tbody></table></div>'


def _get_css(primary_color: str, accent_color: str) -> str:
    return f"""
:root {{
  --primary: {primary_color};
  --accent: {accent_color};
  --bg: #f8fafc;
  --surface: #ffffff;
  --border: #e2e8f0;
  --text: #1e293b;
  --text-muted: #64748b;
  --text-light: #94a3b8;
  --success: #10b981;
  --warning: #f59e0b;
  --danger: #ef4444;
  --radius: 12px;
}}

* {{ margin: 0; padding: 0; box-sizing: border-box; }}

html {{
  scroll-behavior: smooth;
  font-size: 16px;
}}

body {{
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.7;
  -webkit-font-smoothing: antialiased;
}}

/* Header */
.guide-header {{
  background: linear-gradient(135deg, var(--primary) 0%, color-mix(in srgb, var(--primary) 70%, black) 100%);
  color: white;
  padding: 2rem 2rem;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 4px 20px rgba(0,0,0,0.15);
}}

.header-inner {{
  max-width: 1400px;
  margin: 0 auto;
  display: flex;
  justify-content: space-between;
  align-items: center;
  flex-wrap: wrap;
  gap: 1rem;
}}

.header-brand {{
  display: flex;
  align-items: center;
  gap: 1rem;
}}

.header-logo {{
  width: 56px;
  height: 56px;
  border-radius: 12px;
  object-fit: contain;
  background: rgba(255,255,255,0.15);
  padding: 4px;
}}

.header-title {{
  font-size: 1.5rem;
  font-weight: 700;
  letter-spacing: -0.02em;
}}

.header-subtitle {{
  font-size: 0.875rem;
  opacity: 0.8;
  font-weight: 400;
}}

.header-meta {{
  display: flex;
  align-items: center;
  gap: 0.75rem;
  flex-wrap: wrap;
}}

.completeness-badge {{
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  font-size: 0.8rem;
  background: rgba(255,255,255,0.15);
  padding: 0.35rem 0.75rem;
  border-radius: 999px;
  backdrop-filter: blur(4px);
}}

.completeness-score {{
  background: rgba(255,255,255,0.25);
  font-weight: 600;
}}

/* Layout */
.guide-layout {{
  max-width: 1400px;
  margin: 0 auto;
  display: grid;
  grid-template-columns: 280px 1fr;
  gap: 0;
  min-height: calc(100vh - 120px);
}}

/* Sidebar */
.guide-sidebar {{
  position: sticky;
  top: 90px;
  height: calc(100vh - 90px);
  overflow-y: auto;
  border-right: 1px solid var(--border);
  background: var(--surface);
}}

.sidebar-inner {{
  padding: 1.5rem 1rem;
}}

.toc-header {{
  font-size: 0.7rem;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--text-muted);
  margin-bottom: 0.75rem;
}}

.completeness-bar-wrap {{
  height: 4px;
  background: var(--border);
  border-radius: 2px;
  margin-bottom: 1.25rem;
  overflow: hidden;
}}

.completeness-bar {{
  height: 100%;
  background: linear-gradient(90deg, var(--accent), var(--success));
  border-radius: 2px;
  transition: width 0.6s ease;
}}

.toc-list {{
  list-style: none;
}}

.toc-item {{
  margin-bottom: 2px;
}}

.toc-link {{
  display: flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.45rem 0.75rem;
  border-radius: 8px;
  font-size: 0.835rem;
  color: var(--text-muted);
  text-decoration: none;
  transition: all 0.15s;
}}

.toc-link:hover {{
  background: var(--bg);
  color: var(--text);
}}

.toc-link.active {{
  background: color-mix(in srgb, var(--accent) 12%, transparent);
  color: var(--accent);
  font-weight: 600;
}}

.toc-icon {{
  display: inline-flex;
  flex-shrink: 0;
}}

.toc-icon-found {{ color: var(--success); }}
.toc-icon-partial {{ color: var(--warning); }}
.toc-icon-missing {{ color: var(--danger); }}

.toc-status-missing .toc-link {{ opacity: 0.7; }}

/* Main Content */
.guide-content {{
  padding: 2rem 3rem 4rem;
  max-width: 900px;
}}

/* Sections */
.section {{
  margin-bottom: 3rem;
  padding: 2rem;
  background: var(--surface);
  border-radius: var(--radius);
  border: 1px solid var(--border);
  scroll-margin-top: 100px;
  transition: box-shadow 0.2s;
}}

.section:hover {{
  box-shadow: 0 4px 20px rgba(0,0,0,0.04);
}}

.section-missing {{
  border-color: #fed7aa;
  background: linear-gradient(135deg, #fffbeb 0%, #fff7ed 100%);
}}

.section-partial {{
  border-color: #fde68a;
  background: linear-gradient(135deg, #fffbeb 0%, #fefce8 100%);
}}

.section-header {{
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  flex-wrap: wrap;
  gap: 0.5rem;
  margin-bottom: 1.25rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid var(--border);
}}

.section-missing .section-header {{ border-bottom-color: #fed7aa; }}
.section-partial .section-header {{ border-bottom-color: #fde68a; }}

.section-title {{
  font-size: 1.35rem;
  font-weight: 700;
  color: var(--primary);
  letter-spacing: -0.01em;
}}

.section-badges {{
  display: flex;
  align-items: center;
  gap: 0.5rem;
  flex-wrap: wrap;
}}

.status-badge {{
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  font-size: 0.75rem;
  font-weight: 600;
  padding: 0.3rem 0.7rem;
  border-radius: 999px;
}}

.status-missing {{
  background: #fef3c7;
  color: #b45309;
}}

.status-partial {{
  background: #fef9c3;
  color: #a16207;
}}

.verified-date {{
  font-size: 0.72rem;
  color: var(--text-light);
}}

/* Section body typography */
.section-body h3 {{
  font-size: 1.1rem;
  font-weight: 600;
  color: var(--text);
  margin: 1.5rem 0 0.75rem;
}}

.section-body h4 {{
  font-size: 0.95rem;
  font-weight: 600;
  color: var(--text-muted);
  margin: 1.25rem 0 0.5rem;
}}

.section-body p {{
  margin-bottom: 0.75rem;
  color: var(--text);
}}

.section-body ul {{
  margin: 0.5rem 0 1rem 1.25rem;
  list-style: disc;
}}

.section-body ul.numbered {{
  list-style: decimal;
}}

.section-body li {{
  margin-bottom: 0.35rem;
  padding-left: 0.25rem;
}}

.section-body strong {{
  font-weight: 600;
  color: var(--text);
}}

.section-body code {{
  background: var(--bg);
  padding: 0.15em 0.4em;
  border-radius: 4px;
  font-size: 0.9em;
  color: var(--accent);
}}

.section-body a {{
  color: var(--accent);
  text-decoration: underline;
  text-decoration-color: color-mix(in srgb, var(--accent) 30%, transparent);
  text-underline-offset: 2px;
}}

.section-body a:hover {{
  text-decoration-color: var(--accent);
}}

/* Tables */
.table-wrap {{
  overflow-x: auto;
  margin: 1rem 0;
  border-radius: 8px;
  border: 1px solid var(--border);
}}

.table-wrap table {{
  width: 100%;
  border-collapse: collapse;
  font-size: 0.88rem;
}}

.table-wrap th {{
  background: var(--bg);
  font-weight: 600;
  text-align: left;
  padding: 0.7rem 1rem;
  border-bottom: 2px solid var(--border);
  color: var(--text);
  white-space: nowrap;
}}

.table-wrap td {{
  padding: 0.6rem 1rem;
  border-bottom: 1px solid var(--border);
  color: var(--text);
}}

.table-wrap tr:last-child td {{
  border-bottom: none;
}}

.table-wrap tr:hover td {{
  background: var(--bg);
}}

/* Sources */
.source-links {{
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.4rem;
  margin-top: 1.25rem;
  padding-top: 1rem;
  border-top: 1px solid var(--border);
}}

.source-label {{
  font-size: 0.72rem;
  font-weight: 600;
  color: var(--text-light);
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin-right: 0.25rem;
}}

.source-chip {{
  display: inline-flex;
  align-items: center;
  gap: 0.3rem;
  font-size: 0.72rem;
  color: var(--accent);
  background: color-mix(in srgb, var(--accent) 8%, transparent);
  padding: 0.25rem 0.6rem;
  border-radius: 999px;
  text-decoration: none;
  transition: all 0.15s;
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}}

.source-chip:hover {{
  background: color-mix(in srgb, var(--accent) 15%, transparent);
}}

/* Confidence bar */
.confidence-bar-wrap {{
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-top: 0.75rem;
}}

.confidence-label {{
  font-size: 0.72rem;
  color: var(--text-light);
  white-space: nowrap;
}}

.confidence-track {{
  flex: 1;
  height: 4px;
  background: var(--border);
  border-radius: 2px;
  max-width: 120px;
}}

.confidence-fill {{
  height: 100%;
  background: var(--accent);
  border-radius: 2px;
}}

.empty-msg {{
  color: var(--text-muted);
  font-style: italic;
  padding: 1rem 0;
}}

/* Watermark */
.watermark {{
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  margin-top: 3rem;
  padding: 1rem;
  font-size: 0.8rem;
  color: var(--text-light);
  border-top: 1px solid var(--border);
}}

/* Mobile */
.mobile-toc-toggle {{
  display: none;
  position: fixed;
  bottom: 1.5rem;
  right: 1.5rem;
  width: 48px;
  height: 48px;
  border-radius: 50%;
  background: var(--primary);
  color: white;
  border: none;
  cursor: pointer;
  z-index: 200;
  box-shadow: 0 4px 15px rgba(0,0,0,0.2);
  align-items: center;
  justify-content: center;
}}

@media (max-width: 900px) {{
  .guide-layout {{
    grid-template-columns: 1fr;
  }}

  .guide-sidebar {{
    position: fixed;
    left: -300px;
    top: 0;
    width: 280px;
    height: 100vh;
    z-index: 150;
    transition: left 0.3s ease;
    border-right: 1px solid var(--border);
    box-shadow: 4px 0 20px rgba(0,0,0,0.1);
  }}

  .guide-sidebar.open {{
    left: 0;
  }}

  .guide-content {{
    padding: 1.5rem 1rem 3rem;
  }}

  .section {{
    padding: 1.25rem;
  }}

  .mobile-toc-toggle {{
    display: flex;
  }}

  .header-title {{
    font-size: 1.2rem;
  }}

  .guide-header {{
    padding: 1rem;
  }}
}}

/* Print */
@media print {{
  .guide-header {{
    position: relative;
    box-shadow: none;
    print-color-adjust: exact;
    -webkit-print-color-adjust: exact;
  }}

  .guide-sidebar, .mobile-toc-toggle {{
    display: none !important;
  }}

  .guide-layout {{
    grid-template-columns: 1fr;
  }}

  .guide-content {{
    padding: 0;
    max-width: 100%;
  }}

  .section {{
    break-inside: avoid;
    page-break-inside: avoid;
    box-shadow: none;
    border: 1px solid #ddd;
  }}

  .watermark {{
    page-break-before: avoid;
  }}

  body {{
    background: white;
  }}
}}
"""


def _get_js() -> str:
    return """
(function() {
  // Scroll spy for TOC active state
  const sections = document.querySelectorAll('.section');
  const tocLinks = document.querySelectorAll('.toc-link');

  function updateActiveToc() {
    let current = '';
    sections.forEach(function(section) {
      const rect = section.getBoundingClientRect();
      if (rect.top <= 150) {
        current = section.id;
      }
    });
    tocLinks.forEach(function(link) {
      link.classList.toggle('active', link.getAttribute('data-section') === current);
    });
  }

  window.addEventListener('scroll', updateActiveToc, { passive: true });
  updateActiveToc();

  // Smooth scroll for TOC links
  tocLinks.forEach(function(link) {
    link.addEventListener('click', function(e) {
      e.preventDefault();
      var target = document.getElementById(this.getAttribute('data-section'));
      if (target) {
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
      // Close mobile sidebar
      document.getElementById('guideSidebar').classList.remove('open');
    });
  });

  // Mobile TOC toggle
  var toggleBtn = document.getElementById('mobileTocToggle');
  var sidebar = document.getElementById('guideSidebar');
  if (toggleBtn) {
    toggleBtn.addEventListener('click', function() {
      sidebar.classList.toggle('open');
    });
  }

  // Close sidebar on outside click (mobile)
  document.addEventListener('click', function(e) {
    if (sidebar.classList.contains('open') &&
        !sidebar.contains(e.target) &&
        e.target !== toggleBtn) {
      sidebar.classList.remove('open');
    }
  });
})();
"""
